POST http://localhost:5001/api/auth/refresh HTTP/1.1
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImFzZCIsImVtYWlsIjoiQVNEQGFzZC5ydCIsImlhdCI6MTYzNzM3MTc4NiwiZXhwIjoxNjM5OTYzNzg2fQ.uqJuShz0cO9KlHEQ22iScafhkK_kg0rGHk5kyPIb0io"
}
