POST http://localhost:5000/api/auth/sign-up HTTP/1.1
Content-Type: application/json

{
  "user": {
    "nickname": "test2",
    "email": "test@mail.com"
  },
  "passwordCrypt": {
    "iv": "a8991adcf7584ca6a55692f2b9532b73",
    "content": "a1a5371eb685112f66d30f"
  },
  "ua": {
    "ip": "123.123.123.123"
  }
}
