const {
  env: {
    ACCESS_TOKEN_SECRET,
    ACCESS_TOKEN_TIME,
    REFRESH_TOKEN_SECRET,
    REFRESH_TOKEN_TIME
  }
} = process;

module.exports = {
  REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_TIME,
  ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_TIME,

  MAX_DEVICE_AMOUNT: 3,
  SALT_ROUNDS: 6
}
